Fix graph not showing bug
PrestaShop/statsproduct pull request #21
Opened 2021-06-08 06:10 UTC by daresh

Fix statistics graph not working for PHP 7.

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Products stats graph not showing bug fix related to PHP version.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #13178
| How to test?      | Just go to Statistics - Product detail and check if the graph works
| Possible impacts? | Rather none.

2021-06-08 06:44 UTC, kpodemski requested changes

2021-06-08 06:44 UTC, kpodemski commented on statsproduct.php
> +		$this->query = [];
It seems that indentation is wrong

2021-06-08 06:47 UTC, daresh commented on statsproduct.php
> +		$this->query = [];
Indeed, how to modify it now?

2021-06-08 06:47 UTC, kpodemski commented on statsproduct.php
> +		$this->query = [];
```suggestion
		  $this->query = [];
```

2021-06-08 06:48 UTC, kpodemski commented on statsproduct.php
> +		$this->query = [];
Done ;)

2021-06-08 06:48 UTC, kpodemski approved these changes

2021-06-08 06:49 UTC, kpodemski approved these changes

2021-06-08 06:50 UTC, kpodemski commented
Thanks @daresh 

Next time remember to use the `dev` branch 👍

2021-06-08 07:32 UTC, Progi1984 approved these changes

2021-06-08 07:53 UTC, daresh commented
> Thanks @daresh
> 
> Next time remember to use the `dev` branch 👍

I'll try, but I'm not very fluent in GitHub, trying my best to help with bugs that I find.

2021-06-08 07:54 UTC, daresh commented on statsproduct.php
> +		$this->query = [];
Thanks for help :)

2021-06-15 12:41 UTC, khouloudbelguith commented
Hi @daresh,

It is ok :heavy_check_mark: 

**Without PR**
![image](https://user-images.githubusercontent.com/16067358/122052462-041b4400-cde6-11eb-8e02-d862272d8c76.png)

**With PR**
![image](https://user-images.githubusercontent.com/16067358/122052512-0f6e6f80-cde6-11eb-8581-cfe6a6339120.png)


I checked with 177x, 178x and the develop branch.

Thanks!

2021-06-15 12:52 UTC, merged

2021-06-15 12:52 UTC, Progi1984 commented
Thanks @daresh & @khouloudbelguith